version: '3.7'

services:
    api:
        build:
          context: ./simpleapi
        container_name: api
        ports:
          - 8080:8080
        networks:
          - app-network
        depends_on:
          - db
        platform: linux/amd64

    db:
        build:
          context: ./db
        container_name: db
        networks:
          - app-network
        volumes:
          - sql-data:/var/lib/postgresql/data
        env_file:
          - .env
        platform: linux/amd64

    proxy:
        build:
          context: proxy
        container_name: proxy
        ports:
          - 80:80
        networks:
          - app-network
        depends_on:
          - api
        platform: linux/amd64

    frontend:
      build:
        context: ./devops-front
      container_name: frontend
      ports:
        - 8082:80
      networks:
        - app-network
      depends_on:
        - api
      platform: linux/amd64

networks:
  app-network:

volumes:
  sql-data: