- name: Run App
  docker_container:
    name: api
    image:  lzablit1/td-02-cicd-api:1.0
    ports: "8080:8080"
    networks:
      - name: app-network
    pull: true
    recreate: true
    platform: linux/amd64