name: Test Backend
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    env:
      working-directory: ./simpleapi
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v4

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: maven
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=laura-zab_td-02-cicd